### ISSUE TITLE
pls fix my source code :v

### ISSUE THREAD

**Issue by Izaac9236** [byteandahalf/Galacticraft-PE#6]
fix my source code

**Comment by byteandahalf** [comment]
wut

**Comment by Izaac9236** [comment]
isaac300😭😭🙋🙋

**Comment by Izaac9236** [comment]
#ByteEvil 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by TrinityDevelopers** [comment]
dude Isaac you make no sense.

**Comment by byteandahalf** [comment]
lol ^

**Comment by Izaac9236** [comment]
TRINITY FIX MY SOURCE CODE :P aaaaaaa teach me addons like a byteandahalf aaaaaaaaaaaaaaaaaaaa ¤_¤
